# Generated by Django 2.2.12 on 2020-05-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0280_userprofile_presence_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme_detection',
            field=models.BooleanField(default=True),
        ),
    ]
