# Generated by Django 2.2.12 on 2020-05-15 14:26

from django.db import migrations, models

COLOR_SCHEME_AUTOMATIC = 1
class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0280_userprofile_presence_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='night_mode',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='color_scheme',
            field=models.PositiveSmallIntegerField(default=COLOR_SCHEME_AUTOMATIC),
        ),
    ]
